import os
from typing import Dict, List

def list_files(repo_path: str, extension: str = ".py") -> List[str]:
    """
    Lista todos os arquivos com a extensão fornecida no repositório, ignorando pastas comuns de ruído.
    """
    found_files = []
    ignored_dirs = {'.git', '__pycache__', '.venv', 'venv', 'env', 'build', 'dist', 'node_modules'}
    
    for root, dirs, files in os.walk(repo_path):
        # Remove diretórios ignorados
        dirs[:] = [d for d in dirs if d not in ignored_dirs]
        
        for file in files:
            if file.endswith(extension):
                full_path = os.path.join(root, file)
                # Retorna o caminho relativo ao repo_path
                rel_path = os.path.relpath(full_path, repo_path)
                found_files.append(rel_path)
                
    return found_files

def load_source(repo_path: str, rel_path: str) -> str:
    """
    Carrega o conteúdo de um arquivo.
    """
    full_path = os.path.join(repo_path, rel_path)
    with open(full_path, 'r', encoding='utf-8', errors='ignore') as f:
        return f.read()

def is_generated_code(source: str) -> bool:
    """
    Verifica se o código parece ser gerado automaticamente.
    """
    indicators = [
        "generated by",
        "auto-generated",
        "do not edit",
        "protobuf",
        "thrift",
        "openapi",
        "sqlalchemy"
    ]
    header = source[:1000].lower()
    return any(indicator in header for indicator in indicators)

def is_migration_code(rel_path: str, source: str) -> bool:
    """
    Detects if the code is a database migration.
    """
    path_lower = rel_path.lower()
    if "migrations/" in path_lower or "alembic/" in path_lower:
        return True
    if "Django migrations" in source[:1000]:
        return True
    return False

def is_test_code(rel_path: str) -> bool:
    """
    Detects if the code is a test file.
    """
    path_lower = rel_path.lower()
    filename = os.path.basename(path_lower)
    if filename.startswith("test_") or filename.endswith("_test.py"):
        return True
    if "tests/" in path_lower:
        return True
    return False
