import os
from typing import Dict, List

def list_python_files(repo_path: str) -> List[str]:
    """
    Lista todos os arquivos Python (.py) no repositório, ignorando pastas comuns de ruído.
    """
    python_files = []
    ignored_dirs = {'.git', '__pycache__', '.venv', 'venv', 'env', 'build', 'dist'}
    
    for root, dirs, files in os.walk(repo_path):
        # Remove diretórios ignorados
        dirs[:] = [d for d in dirs if d not in ignored_dirs]
        
        for file in files:
            if file.endswith('.py'):
                full_path = os.path.join(root, file)
                # Retorna o caminho relativo ao repo_path
                rel_path = os.path.relpath(full_path, repo_path)
                python_files.append(rel_path)
                
    return python_files

def load_source(repo_path: str, rel_path: str) -> str:
    """
    Carrega o conteúdo de um arquivo.
    """
    full_path = os.path.join(repo_path, rel_path)
    with open(full_path, 'r', encoding='utf-8', errors='ignore') as f:
        return f.read()

def is_generated_code(source: str) -> bool:
    """
    Verifica se o código parece ser gerado automaticamente.
    """
    indicators = [
        "generated by",
        "auto-generated",
        "do not edit",
        "protobuf",
        "thrift",
        "openapi",
        "sqlalchemy"
    ]
    header = source[:1000].lower()
    return any(indicator in header for indicator in indicators)
